spring.application.name=inkit-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/inkit
spring.datasource.username=postgres
spring.datasource.password=Prashant29@

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

jwt.secret=inkit-secret-key
jwt.expiry=86400000
