spring.application.name=inkit-backend
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/inkit
spring.datasource.username=postgres
spring.datasource.password=Prashant29@

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

jwt.secret=${JWT_SECRET:inkit-dev-secret-key-change-this-to-32-plus-bytes}
jwt.expiry=86400000
spring.jpa.hibernate.ddl-auto=update

# e-Courts API Configuration
ecourt.api.url=https://webapi.ecourtsindia.com/api/partner/case/
ecourt.api.token=eci_live_pq3acqhjp9nxnz6py65u6hsp2dvnz7em
